#!/bin/bash

function show_help() {
  echo "\
Usage: $(cmd) INSTANCE_NAME
       $(cmd) --TAG_NAME TAG_VALUE

Find EC2 instances by tag values and show private ip address. Instances are
matched if they contain the given tag value. If no tag name is specified then
'Name' tag is used.

AWS CLI and JQ are required. Set default AWS CLI profile or environment
variables to control AWS credentials."
}

function cmd() {
  basename "$0"
}

tag_name="Product"

case $1 in
  --*)
    tag_name="${1#--}"
    shift
  ;;
  -h)
    show_help
    exit
  ;;
  *)
    tag_name="Name"
  ;;
esac

tag_value="${1}"

if [[ "$tag_value" == "" ]]; then
  show_help
  exit 1
fi

tag_value="$1"

instances_json=$(aws ec2 describe-instances \
  --filters "Name=tag:${tag_name},Values=*${tag_value}*")

jq -r '.Reservations[] | .Instances[] |
    {
      ip: .PrivateIpAddress,
      name: ((.Tags[] | select(.Key == "Name")) // {}) | .Value,
      env: ((.Tags[] | select(.Key == "Environment")) // {}) | .Value
    } |
    join(" ")' < <(echo "${instances_json}")
